# Generated by Django 2.2.13 on 2022-10-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20221010_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='MyModel',
        ),
    ]
