# Generated by Django 2.2.13 on 2022-10-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20221010_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Recipe',
        ),
    ]
