# Generated by Django 2.2.13 on 2022-10-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20221010_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='mobile_number',
            new_name='Time',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
    ]
