# Generated by Django 2.2.13 on 2022-10-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20221010_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Noraml', 'Normal'), ('Hard', 'Hard')], default='Easy', max_length=24),
        ),
    ]
