# Generated by Django 2.2.13 on 2022-10-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ResText',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
