# Generated by Django 2.2.13 on 2022-10-10 15:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_recipe_restext'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Ingredients',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
