# Generated by Django 2.2.13 on 2022-10-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_recipe_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categoriesss',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Salads', 'Salads'), ('Main dishes', 'Main dishes'), ('Desserts', 'Desserts')], default='Main dishes', max_length=24),
        ),
    ]
