# Generated by Django 2.2.13 on 2022-10-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20221011_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='upload',
        ),
    ]
