# Generated by Django 2.2.13 on 2022-10-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_recipe_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
