# Generated by Django 2.2.13 on 2022-10-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_recipe_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
