# Generated by Django 2.2.13 on 2022-10-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0033_auto_20221011_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='upload',
            field=models.ImageField(upload_to='media/uploads'),
        ),
    ]
