# Generated by Django 2.2.13 on 2022-10-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20221025_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
