# Generated by Django 2.2.13 on 2022-10-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20221025_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=24)),
                ('date', models.DateTimeField()),
                ('Text', models.TextField()),
            ],
        ),
    ]
